### ISSUE TITLE
Archivos fuentes partes impresas

### ISSUE THREAD

**Issue by hulkco** [BilbaoDynamics/Pinchy#2]
Hola, gracias por compartir su proyecto, podrian compartir los ficheros fuente de las partes impresas y la medida de la Matriz de Leds, gracias

**Comment by BilbaoDynamics** [comment]
Buenas tardes Gustavo,

Todos los archivos imprimibles necesarios están en la carpeta Chasis (https://github.com/BilbaoDynamics/Pinchy/tree/master/Chasis). En cuanto a la matriz de LEDs, el driver que utilizamos es este (https://www.sparkfun.com/datasheets/Components/General/COM-09622-MAX7219-MAX7221.pdf) y la matriz esta (https://www.dropbox.com/s/1uju2v4d2x47efw/matriz.pdf?dl=0). 

Un saludo, BD team.
